s5: presentation.txt
	pandoc -t s5 -s --self-contained presentation.txt -o maximizingfossvalue_s5.html

slidy: presentation.txt
	pandoc -t slidy -s --self-contained presentation.txt -o maximizingfossvalue_slidy.html



