s5: what_did_I_just_agree_to.txt
	pandoc -t s5 -s --self-contained what_did_I_just_agree_to.txt -o wdijat_s5.html

slidy: what_did_I_just_agree_to.txt
	pandoc -t slidy -s --self-contained what_did_I_just_agree_to.txt -o wdijat_slidy.html



